USRSE/usrse23

pages/dates.md

fix: date -> 2023

---

README.md

Fixes #5 .
We don't want to assume that people know how to view the site locally. This adds instructions.
cc @mrmundt @cabejackson @manning-ncsa @jmelot

Add instructions for previewing locally

---

pages/notebook-submissions.md
pages/participate.md

- Add a new page containing the submission guidelines for the Computational Notebook submission category
- Add a link pointing to said page in the "Participating" top-level page
- The text is minimally adapted from the working draft titled "Notebook Submissions" in the shared Drive folder
- We expect to refine the text based on feedback (warmly encouraged!), both during this PR and in subsequent PRs
cc @mrmundt @cabejackson @manning-ncsa @jmelot

Add Notebook Submissions page

---

pages/participate.md

Added a talk section to the participate page.
To encourage submissions by people who are not interested in writing a paper.

Added talks to call for participation

---

index.html

Per #15 , this adds a countdown timer. The timer is from a free website so it links to that website, but I don't see that as a problem.
We want to build the hype!
Preview:

Add Countdown Timer to Index

---

assets/css/main.css

Change main site font to Roboto, to match main us-rse.org site.
This matches the preferred font in the main us-rse.org site, and IMO is more readable.
- [n/a] I have updated the README.md if necessary

Use Roboto font to match main US-RSE site

---

_posts/2023-03-13-march-cc-blog.md

This PR adds a blog post detailing the March community call and adding a link to the recording so people can go watch it.
Since the CC was primarily used to talk about the inspiration and process for notebook submissions, we want it to get more traffic.

Blog Post for March Community Call

---

pages/organization.md

There were a few changes in the organization information. This updates those and adds affiliations.
We want accurate information about the committee.

Update Organization Page Information

---

index.html
pages/organization.md
pages/participate.md

The email on the Participate page is incorrect; this provides the correct one.
We don't want emails to bounce.

Update Contact Email

---

_posts/2023-03-03-notebook-submission-tutorial.md

Added post about notebook submission tutorial

---

_config.yml
pages/sponsor.md

This is the initial push of the Sponsor page. It needs review with the main Google Doc and a good place in the website for visibility. 
This is required for US-RSE 2023 conference. 

added sponsor page

---

_posts/2023-04-03-travel-info.md
pages/attend/attend.md
pages/attend/travel.md

This PR adds the initial information about the venue and nearby hotels, plus other travel information (e.g, driving/parking instructions).
We want to inform people of details about the venue.

Add travel/venue information

---

_posts/2023-04-20-volunteer-call.md

Add a blog post about the call for reviewers so anyone who visits the main conference page is aware that we are looking for volunteers.

Blog Post: Call for Reviewers

---

pages/sponsor/sponsor.md

Updated sponsor levels table and additional note for support opportunities.
Changed Sponsor page with two edits. One for number of ticket for silver level and the other one for additional comment regarding sponsorship opportunities for small businesses and startups.
The change was approved by Sponsor Chairs and General Chairs. The change fixed the wording in sponsorship levels table and adds additional comments for small businesses/ and startups. 

update sponsor page

---

pages/sponsor/sponsor.md

Added few suggested items for additional sponsor opportunities
Added three more options for sponsor opportunities
This change was added after reviewing the sponsor contact with Sandra and Julia. 

Updated Sponsor Page

---

_posts/2023-05-05-extend-papers-final.md
index.html
pages/about/dates.md
pages/participate/participate.md

Post the final extension for papers and notebooks.

Final extension for papers/notebooks - May 15

---

.github/workflows/linting.yaml
_posts/2023-05-30-hotel-codes.md
pages/attend/travel.md

We have information about hotel blocks now. This PR adds a post about that and adds the actual information.

Add hotel accomodation information

---

_posts/2023-06-05-price-registration.md
pages/attend/registration.md

This adds information about the early bird and regular registration costs so people can begin to plan accordingly.

Announce Registration Cost

---

_posts/2023-06-14-extend-papers-notification-final.md
pages/about/dates.md
pages/participate/participate.md

Post an extension for the papers and notebooks notification deadline.

Extend paper notification deadline

---

pages/about/dates.md
pages/participate/participate.md

Postpone camera-ready due date for papers and notebooks

---

index.html
pages/about/dates.md
pages/participate/participate.md

This extension allows us extra time to get out guidelines and standardizes.

Extend camera-ready deadline for all submissions to Aug 28

---

_data/menus/program.yml
_data/navigation.yml
pages/program/bofs.md
pages/program/program.md

The BoFs list is incomplete. This updates that plus makes the program menu more functional now that it actually has useful information.

Update BoFs and program submenu

---

_posts/2023-08-01-registration-open.md
index.html
pages/attend/registration.md

Open Registration

---

pages/program/tutorials.md

There is an additional tutorial that needs to be added to the tutorials page.

Update Tutorial Page

---

pages/attend/registration.md

Eventbrite has some fees that aren't reflected in the table of costs.

Update registration table to reflect Eventbrite fees

---

pages/organization/organization.md
pages/organization/student.md

Added our two student cochairs and their affiliation to both the student.md and organization.md pages
- [NA] I have updated the README.md if necessary

Added student co-chairs to organization pages

---

pages/program/program.md

Update timezone to CT and add note stating that all times are in CT.

Update Timezone to CT

---

_posts/2023-09-07-hotel-block.md

We want to remind folks about the special rates in the hotel blocks.

Reminder about Hotel Blocks

---

_posts/2023-09-07-hotel-block.md
pages/attend/travel.md
pages/program/abstracts/tutorials.md
pages/program/program.md

Doing bad software practice here and putting in two changes at once:
1. Update hotel block information
2. Add tutorial registration links

Update hotel info; add tutorial registration links

---

pages/program/abstracts/bofs.md
pages/program/program.md

We were waiting to add the last BoF to the website until we had confirmation from the author. We now have confirmation, so this PR adds it.

Add 6th BoF's information

---

_posts/2023-09-14-volunteers-wanted.md

Add a post with information on how to volunteer / get a free t-shirt.

Call for In-Person Volunteers

---

_data/menus/attend.yml
_data/navigation.yml
_posts/2023-09-27-covid-policy.md
_posts/2023-10-02-covid-policy.md
pages/attend/attend.md
pages/attend/health.md

We have implemented a mask mandate. This PR adds the information to the website.

Add COVID policy to website

---

index.html

Add Amazon as a bronze sponsor.

Add Amazon as Sponsor

---

pages/program/sessions.md

This adds the title and speakers for the Funder panel.

Add Funder Panel Information

---

_posts/2023-10-11-special-edition.md

This adds a post announcing the special issue in Future Generation Computer Systems.

Announce Special Issue

---

_posts/2023-10-12-streaming.md
pages/program/keynotes.md
pages/program/program.md
pages/program/sessions.md

This PR makes the Zoom registration information available for the Keynote speakers and the Funder panel.

Zoom Registration Information for Keynotes and Funder Panel
